### ISSUE TITLE
I cant login

### ISSUE THREAD

**Issue by dikeckaan** [fedyfausto/RaspberryWebPanel#1]
Hi when i write my username and pass it says wrong how can i fix that (its fresh install)

**Comment by fedyfausto** [comment]
You can change your info on the main config file ;)

Dott. Federico Fausto Santoro



Il giorno 17/ago/2017, alle ore 14:45, Anticolick <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi when i write my username and pass it says wrong how can i fix that (its fresh install)
